version: '3'
services:
  dns:
    image: ghcr.io/oct8l/lancache-dns:latest  ## Pulling DNS server for arm
    env_file: .env
    ports:
      - ${DNS_BIND_IP}:53:53/udp
      - ${DNS_BIND_IP}:53:53/tcp
    restart: always

  monolithic:
    image: ghcr.io/oct8l/lancache-monolithic:latest ## Pulling monolithic for arm
    env_file: .env
    ports:
      - 80:80/tcp
      - 443:443/tcp
    restart: always
    volumes:
      - ${CACHE_ROOT}/cache:/data/cache
      - ${CACHE_ROOT}/logs:/data/logs
