name: Build and Publish

env:
  REGISTRY: ghcr.io/${{ github.repository_owner }}

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  workflow_dispatch:
  schedule:
    - cron: '30 4 1,15 * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - name: Cache Docker layers
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Github Packages
        if: github.event_name != 'pull_request'
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push lancachenet/ubuntu
        run: |
          git clone https://github.com/lancachenet/ubuntu.git
          cd ubuntu
          docker buildx build --platform linux/amd64,linux/arm64/v8,linux/arm/v7 -t ${{ env.REGISTRY }}/lancache-ubuntu --push .
          cd ..

      - name: Build & Push lancachenet/ubuntu-nginx
        run: |
          git clone https://github.com/lancachenet/ubuntu-nginx.git
          cd ubuntu-nginx
          line_number=$(grep -n "FROM lancachenet/ubuntu:latest" Dockerfile | cut -d: -f1)
          sed -i "${line_number}cFROM ${{ env.REGISTRY }}/lancache-ubuntu" Dockerfile
          cat Dockerfile
          docker buildx build --platform linux/amd64,linux/arm64/v8,linux/arm/v7 -t ${{ env.REGISTRY }}/lancache-ubuntu-nginx --push .
          cd ..

      - name: Build & Push lancachenet/monolithic
        run: |
          git clone https://github.com/lancachenet/monolithic.git
          cd monolithic
          line_number=$(grep -n "FROM lancachenet/ubuntu-nginx:latest" Dockerfile | cut -d: -f1)
          sed -i "${line_number}cFROM ${{ env.REGISTRY }}/lancache-ubuntu-nginx" Dockerfile
          cat Dockerfile
          cp ../20_cache.conf overlay/etc/nginx/sites-available/cache.conf.d/root/20_cache.conf
          docker buildx build --platform linux/amd64,linux/arm64/v8,linux/arm/v7 -t ${{ env.REGISTRY }}/lancache-monolithic --push .
          cd ..

      - name: Build & Push lancachenet/generic
        run: |
          git clone https://github.com/lancachenet/generic.git
          cd generic
          line_number=$(grep -n "FROM lancachenet/monolithic:latest" Dockerfile | cut -d: -f1)
          sed -i "${line_number}cFROM ${{ env.REGISTRY }}/lancache-monolithic" Dockerfile
          cat Dockerfile
          docker buildx build --platform linux/amd64,linux/arm64/v8,linux/arm/v7 -t ${{ env.REGISTRY }}/lancache-generic --push .
          cd ..

      - name: Build & Push lancachenet/sniproxy
        run: |
          git clone https://github.com/lancachenet/sniproxy.git
          cd sniproxy
          docker buildx build --platform linux/amd64,linux/arm64/v8,linux/arm/v7 -t ${{ env.REGISTRY }}/lancache-sniproxy --push .
          cd ..

      - name: Build & Push lancachenet/lancache-dns
        run: |
          git clone https://github.com/lancachenet/lancache-dns.git
          cd lancache-dns
          line_number=$(grep -n "FROM lancachenet/ubuntu:latest" Dockerfile | cut -d: -f1)
          sed -i "${line_number}cFROM ${{ env.REGISTRY }}/lancache-ubuntu" Dockerfile
          cat Dockerfile
          docker buildx build --platform linux/amd64,linux/arm64/v8,linux/arm/v7 -t ${{ env.REGISTRY }}/lancache-dns --push .
          cd ..
