name: Build and Publish

env:
  REGISTRY: ghcr.io/${{ github.repository_owner }}

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  workflow_dispatch:
  schedule:
    - cron: '30 4 1,15 * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Cache Docker layers
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Github Packages
        if: github.event_name != 'pull_request'
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push lancachenet/ubuntu
        run: |
          git clone https://github.com/lancachenet/ubuntu.git
          cd ubuntu
          docker buildx build --platform linux/amd64,linux/arm64/v8,linux/arm/v7 -t ${{ env.REGISTRY }}/lancache-ubuntu --push .
          cd ..

      - name: Build & Push lancachenet/ubuntu-nginx
        run: |
          git clone https://github.com/lancachenet/ubuntu-nginx.git
          cd ubuntu-nginx
          line_number=$(grep -n "FROM lancachenet/ubuntu:latest" Dockerfile | cut -d: -f1)
          sed -i "${line_number}cFROM ${{ env.REGISTRY }}/lancache-ubuntu" Dockerfile
          cat Dockerfile
          docker buildx build --platform linux/amd64,linux/arm64/v8,linux/arm/v7 -t ${{ env.REGISTRY }}/lancache-ubuntu-nginx --push .
          cd ..

      - name: Build & Push lancachenet/monolithic
        run: |
          git clone https://github.com/lancachenet/monolithic.git
          cd monolithic
          line_number=$(grep -n "FROM lancachenet/ubuntu-nginx:latest" Dockerfile | cut -d: -f1)
          sed -i "${line_number}cFROM ${{ env.REGISTRY }}/lancache-ubuntu-nginx" Dockerfile
          cat Dockerfile
          cp ../20_cache.conf overlay/etc/nginx/sites-available/cache.conf.d/root/20_cache.conf
          docker buildx build --platform linux/amd64,linux/arm64/v8,linux/arm/v7 -t ${{ env.REGISTRY }}/lancache-monolithic --push .
          cd ..

      - name: Build & Push lancachenet/generic
        run: |
          git clone https://github.com/lancachenet/generic.git
          cd generic
          line_number=$(grep -n "FROM lancachenet/monolithic:latest" Dockerfile | cut -d: -f1)
          sed -i "${line_number}cFROM ${{ env.REGISTRY }}/lancache-monolithic" Dockerfile
          cat Dockerfile
          docker buildx build --platform linux/amd64,linux/arm64/v8,linux/arm/v7 -t ${{ env.REGISTRY }}/lancache-generic --push .
          cd ..

      - name: Build & Push lancachenet/sniproxy
        run: |
          git clone https://github.com/lancachenet/sniproxy.git
          cd sniproxy
          docker buildx build --platform linux/amd64,linux/arm64/v8,linux/arm/v7 -t ${{ env.REGISTRY }}/lancache-sniproxy --push .
          cd ..

      - name: Build & Push lancachenet/lancache-dns
        run: |
          git clone https://github.com/lancachenet/lancache-dns.git
          cd lancache-dns
          line_number=$(grep -n "FROM lancachenet/ubuntu:latest" Dockerfile | cut -d: -f1)
          sed -i "${line_number}cFROM ${{ env.REGISTRY }}/lancache-ubuntu" Dockerfile
          cat Dockerfile
          docker buildx build --platform linux/amd64,linux/arm64/v8,linux/arm/v7 -t ${{ env.REGISTRY }}/lancache-dns --push .
          cd ..
